services:
  mongodb:
    image: mongo:latest
    container_name: trabalho_fullstack
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=123
    volumes:
      - mongodb_trabalho:/data/db

volumes:
  mongodb_trabalho: